animal_friends/config/routes.rb
Rails.application.routes.draw do
  
  root 'animals#index'
  resources :animals

end

animal_friends/app/models/animal.rb
class Animal < ActiveRecord::Base
end

animal_friends/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end

  def show
    @animal = Animal.find(params[:id])
  end

  def new
    @animal = Animal.new
  end

  def create
    Animal.create(animal_params)
    redirect_to(animals_path)
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    @animal.update(animal_params)
    redirect_to(animals_path)
  end

  def destroy
    animal = Animal.find(params[:id])
    # Delete the animal from the db
    animal.destroy
    redirect_to(animals_path)
  end

private 
  def animal_params
    params.require(:animal).permit(:name, :species, :image, :order)
  end

end

animal_friends/app/views/animals/edit.html.erb
<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :species %>
  <%= f.text_field :species %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :order %>
  <%= f.text_field :order %>

  <%= f.submit 'Update Animal' %>
<% end %>

animal_friends/app/views/animals/index.html.erb
<h1>Animals Index</h1>
  <div class="list-group">
    <% @animals.each do |animal|  %>
      <div class="list-group-item">
        <ul class="animal">
          <li><%= link_to(animal.name, animal_path(animal.id)) %></li>
          <li><%= link_to('DELETE', animal_path(animal.id)) %></li>
          <li><%= link_to('EDIT', edit_animal_path(animal.id)) %></li>
        </ul>
      </div>
    <% end %>
  </div>

animal_friends/app/views/animals/new.html.erb
<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :species %>
  <%= f.text_field :species %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :order %>
  <%= f.text_field :order %>

  <%= f.submit 'Create Animal' %>
<% end %>

animal_friends/app/views/animals/show.html.erb
<div class="animal-info">
  <h3><%= @animal.name %></h3>
  <h4><%= @animal.species %></h4>
  <h4><%= @animal.order %></h4>
  <%= image_tag(@animal.image, width: 900) %>

</div>

animal_friends/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnimalFriends</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav>
    <li><%= link_to('Animals', animals_path) %></li>
    <li><%= link_to('New Animal', new_animal_path) %></li>
  </nav>
</header>
<%= yield %>

</body>
</html>